services:
  app:
    build: .
    container_name: movie_be
    ports:
      - "8081:8080"
    env_file:
      - .env
    networks:
      - movie_network

networks:
  movie_network:
    external:
      name: website-wpress_default

volumes:
  db_data:
