name: Deploy movie_be
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    # 1. Chuyển sang self-hosted để dùng runner trên server của bạn
    runs-on: self-hosted 
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy to Server
        env:
            # Đảm bảo bạn đã tạo các biến trong GitHub Settings > Secrets
            HOST: ${{ secrets.HOST }}
            DB_DATABASE: ${{ secrets.DB_DATABASE }}
            DB_USER: ${{ secrets.DB_USER }}
            DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
            DB_DIALECT: ${{ secrets.DB_DIALECT }}



        run: |
          # 2. Xóa hết nội dung cũ trong thư mục production (nếu cần sạch) 
          # hoặc bạn có thể bỏ qua dòng này nếu muốn giữ file cũ
          rm -rf /root/movie_be
          
          # 3. Copy source code vừa checkout từ github vào thư mục production. nó chỉ copy những thằng con, 
          # không phải copy rồi nén lại bên trong thư mục như lệnh git clone thông thường
          cp -r . /root/movie_be
          
          # 4. Di chuyển vào thư mục và chạy docker-compose
          cd /root/movie_be
          
          # Tạo file .env tạm thời trên server để docker-compose đọc
          echo "HOST=$HOST" > .env
          echo "DB_DATABASE=$DB_DATABASE" > .env
          echo "DB_USER=$DB_USER" > .env
          echo "DB_PASSWORD=$DB_PASSWORD" > .env
          echo "DB_DIALECT=$DB_DIALECT" > .env


          
          # 5. Dừng và khởi động lại container có --build là nó tự biết xóa thư viện cũ
          docker compose down
          docker compose up -d --build